project_name: "LED 6400x2000"
output:
  name: "Main LED 6400x2000"
  target_width: 6400
  target_height: 2000
  refresh_rate: 60
  color_space: "bt709"
  color_range: "full"
  bit_depth: 8
canvas:
  name: "Main Canvas"
  width: 6400
  height: 2000
  fps: 60
  layout:
    - name: "Processor Input 1"
      x: 0
      y: 0
      width: 3840
      height: 2000
    - name: "Processor Input 2"
      x: 3840
      y: 0
      width: 2560
      height: 2000
