project_name: "LED 7680x2160"
output:
  name: "Main LED 7680x2160"
  target_width: 7680
  target_height: 2160
  refresh_rate: 60
  color_space: "bt709"
  color_range: "full"
  bit_depth: 8
canvas:
  name: "Main Canvas"
  width: 7680
  height: 2160
  fps: 60
  layout:
    - name: "Processor Input 1"
      x: 0
      y: 0
      width: 3840
      height: 2160
    - name: "Processor Input 2"
      x: 3840
      y: 0
      width: 3840
      height: 2160
